version: "3.1"
services:
  mongodb:
      image: mongo:3.4
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: "npm run dev"
    expose:
      - "7999"
      - '27017'
      - "1337"
    external_links: ["localhost:mongodb"]
    volumes:
      - .:/opt/app
      # workaround to prevent host node_modules from accidently getting mounted in container
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
    notused:
