version: "3.1"
services:
  mongodb:
      image: mongo:3.4
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      # volumes:
      #   - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: "npm run dev"
    ports:
      - '127.0.0.1:7999:7999'
    expose:
      - '27017'
    external_links: ["mongodb:mongodb"]
    volumes:
      - .:/opt/app
      # workaround to prevent host node_modules from accidently getting mounted in container
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb

volumes:
    notused:
