version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
    #  - ./data:/data/db
    ports:
      - "27017:27017"
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: "npm run dev"
    expose:
      - "7999"
      - "27017"
      - "1337"
    volumes:
      - .:/opt/app
      # workaround to prevent host node_modules from accidently getting mounted in container
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
    notused:
